//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.CalendarPages", typeof(CalendarPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Appointment.
        /// </summary>
        public static string CancelAppointment {
            get {
                return ResourceManager.GetString("CancelAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Reason.
        /// </summary>
        public static string CancellationReason {
            get {
                return ResourceManager.GetString("CancellationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment was successfully cancelled..
        /// </summary>
        public static string CancelSuccessful {
            get {
                return ResourceManager.GetString("CancelSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Scheduled.
        /// </summary>
        public static string CurrentlyScheduled {
            get {
                return ResourceManager.GetString("CurrentlyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Unavailability.
        /// </summary>
        public static string EditUnavail {
            get {
                return ResourceManager.GetString("EditUnavail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just the appointment for {0}.
        /// </summary>
        public static string JustSingle {
            get {
                return ResourceManager.GetString("JustSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment was successfully moved..
        /// </summary>
        public static string MoveSuccessful {
            get {
                return ResourceManager.GetString("MoveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointments in the series selected below.
        /// </summary>
        public static string MultipleAppointments {
            get {
                return ResourceManager.GetString("MultipleAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select more than 1 appointment in the series to move..
        /// </summary>
        public static string MustSelectSomeInSeries {
            get {
                return ResourceManager.GetString("MustSelectSomeInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        public static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Sessions to Schedule.
        /// </summary>
        public static string NbrToSchedule {
            get {
                return ResourceManager.GetString("NbrToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment is part of a series that occurs every {2} weeks on {0} at {1}..
        /// </summary>
        public static string PartOfSeries {
            get {
                return ResourceManager.GetString("PartOfSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appointment is part of a weekly series on {0} at {1}..
        /// </summary>
        public static string PartOfWeeklySeries {
            get {
                return ResourceManager.GetString("PartOfWeeklySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Unavailability.
        /// </summary>
        public static string RemoveUnavail {
            get {
                return ResourceManager.GetString("RemoveUnavail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this unavailability period?.
        /// </summary>
        public static string RemoveUnavailInstr {
            get {
                return ResourceManager.GetString("RemoveUnavailInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Make-up Session.
        /// </summary>
        public static string ScheduleMakeup {
            get {
                return ResourceManager.GetString("ScheduleMakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Unavailability.
        /// </summary>
        public static string ScheduleUnavail {
            get {
                return ResourceManager.GetString("ScheduleUnavail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment series was successfully moved..
        /// </summary>
        public static string SeriesMoved {
            get {
                return ResourceManager.GetString("SeriesMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appointment is part of a series of appointments for {0} at {1}. What would you like to reschedule?.
        /// </summary>
        public static string SeriesSelInstr {
            get {
                return ResourceManager.GetString("SeriesSelInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Schedule.
        /// </summary>
        public static string ServiceSchedule {
            get {
                return ResourceManager.GetString("ServiceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unavailability period was successfully created..
        /// </summary>
        public static string UnavailabilityCreated {
            get {
                return ResourceManager.GetString("UnavailabilityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unavailability period was successfully deleted..
        /// </summary>
        public static string UnavailabilityRemoved {
            get {
                return ResourceManager.GetString("UnavailabilityRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unavailability period was successfully updated..
        /// </summary>
        public static string UnavailabilityUpdated {
            get {
                return ResourceManager.GetString("UnavailabilityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Schedule.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
