//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClaimsPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClaimsPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.ClaimsPages", typeof(ClaimsPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pending.
        /// </summary>
        public static string AllActive {
            get {
                return ResourceManager.GetString("AllActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        public static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount/ Reason.
        /// </summary>
        public static string AmountReason {
            get {
                return ResourceManager.GetString("AmountReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim was successfully closed..
        /// </summary>
        public static string ClaimClosed {
            get {
                return ResourceManager.GetString("ClaimClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim issue has been marked as resolved..
        /// </summary>
        public static string ClaimIssueResolved {
            get {
                return ResourceManager.GetString("ClaimIssueResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim was successfully reset to the first applicable state..
        /// </summary>
        public static string ClaimReset {
            get {
                return ResourceManager.GetString("ClaimReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} claims successfully processed.
        /// </summary>
        public static string ClaimsProcessed {
            get {
                return ResourceManager.GetString("ClaimsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment was successfully added to the claim..
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were the claims downloaded and submitted successfully?.
        /// </summary>
        public static string ConfirmSubmit {
            get {
                return ResourceManager.GetString("ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Government Batch.
        /// </summary>
        public static string DownloadGovt {
            get {
                return ResourceManager.GetString("DownloadGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download HCFA.
        /// </summary>
        public static string DownloadHCFA {
            get {
                return ResourceManager.GetString("DownloadHCFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File To Process.
        /// </summary>
        public static string FileToProcess {
            get {
                return ResourceManager.GetString("FileToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating.
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} issues.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line #.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lines total.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Days Ago.
        /// </summary>
        public static string MaxDays {
            get {
                return ResourceManager.GetString("MaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Days Ago.
        /// </summary>
        public static string MinDays {
            get {
                return ResourceManager.GetString("MinDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active government programs to collect payments from..
        /// </summary>
        public static string NoActiveGovtPrograms {
            get {
                return ResourceManager.GetString("NoActiveGovtPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active insurance companies on the account to process claims for..
        /// </summary>
        public static string NoActiveInsurance {
            get {
                return ResourceManager.GetString("NoActiveInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no claims pending government submission selected..
        /// </summary>
        public static string NoClaimsPendingGovtSubSelected {
            get {
                return ResourceManager.GetString("NoClaimsPendingGovtSubSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no claims pending insurance submission selected..
        /// </summary>
        public static string NoClaimsPendingInsSubSelected {
            get {
                return ResourceManager.GetString("NoClaimsPendingInsSubSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No claims were marked as paid or denied..
        /// </summary>
        public static string NoClaimsProcessed {
            get {
                return ResourceManager.GetString("NoClaimsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was provided to process..
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pending claims for the selection..
        /// </summary>
        public static string NoPendingClaims {
            get {
                return ResourceManager.GetString("NoPendingClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Payment.
        /// </summary>
        public static string PayGovt {
            get {
                return ResourceManager.GetString("PayGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Payment.
        /// </summary>
        public static string PayInsurance {
            get {
                return ResourceManager.GetString("PayInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was successfully recorded..
        /// </summary>
        public static string PaymentRecorded {
            get {
                return ResourceManager.GetString("PaymentRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment was successfully voided..
        /// </summary>
        public static string PaymentVoided {
            get {
                return ResourceManager.GetString("PaymentVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Payment.
        /// </summary>
        public static string PayPrivate {
            get {
                return ResourceManager.GetString("PayPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Government Issue.
        /// </summary>
        public static string PendGovtIssue {
            get {
                return ResourceManager.GetString("PendGovtIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Government Payment.
        /// </summary>
        public static string PendGovtPay {
            get {
                return ResourceManager.GetString("PendGovtPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Government Submission.
        /// </summary>
        public static string PendGovtSubmission {
            get {
                return ResourceManager.GetString("PendGovtSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending On.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Waiver.
        /// </summary>
        public static string PendingWaiver {
            get {
                return ResourceManager.GetString("PendingWaiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Insurance Payment.
        /// </summary>
        public static string PendInsPay {
            get {
                return ResourceManager.GetString("PendInsPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Insurance Submission.
        /// </summary>
        public static string PendInsSubmission {
            get {
                return ResourceManager.GetString("PendInsSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Insurance Issue.
        /// </summary>
        public static string PendInsSubmissionIssue {
            get {
                return ResourceManager.GetString("PendInsSubmissionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Payment.
        /// </summary>
        public static string PendPay {
            get {
                return ResourceManager.GetString("PendPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy #.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Reconcile.
        /// </summary>
        public static string ReconcileGovt {
            get {
                return ResourceManager.GetString("ReconcileGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in payments recorded.
        /// </summary>
        public static string ReconcilePayment {
            get {
                return ResourceManager.GetString("ReconcilePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve Claim Issue.
        /// </summary>
        public static string ResolveClaim {
            get {
                return ResourceManager.GetString("ResolveClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim submission has been confirmed and the claims were advanced to pending payment..
        /// </summary>
        public static string SubmissionConfirmed {
            get {
                return ResourceManager.GetString("SubmissionConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Claims.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To PDF.
        /// </summary>
        public static string ToPDF {
            get {
                return ResourceManager.GetString("ToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this claim?.
        /// </summary>
        public static string VerifyClose {
            get {
                return ResourceManager.GetString("VerifyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this claim?.
        /// </summary>
        public static string VerifyReset {
            get {
                return ResourceManager.GetString("VerifyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet.
        /// </summary>
        public static string Vet {
            get {
                return ResourceManager.GetString("Vet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim was successfully marked as vetted..
        /// </summary>
        public static string Vetted {
            get {
                return ResourceManager.GetString("Vetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetting.
        /// </summary>
        public static string Vetting {
            get {
                return ResourceManager.GetString("Vetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Notes.
        /// </summary>
        public static string ViewNotes {
            get {
                return ResourceManager.GetString("ViewNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided At.
        /// </summary>
        public static string VoidedAt {
            get {
                return ResourceManager.GetString("VoidedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to void this payment? If so please include a reason for voiding the payment..
        /// </summary>
        public static string VoidInstr {
            get {
                return ResourceManager.GetString("VoidInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Payment.
        /// </summary>
        public static string VoidPayment {
            get {
                return ResourceManager.GetString("VoidPayment", resourceCulture);
            }
        }
    }
}
