//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.ClientPages", typeof(ClientPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Case Worker.
        /// </summary>
        public static string AddCaseWorker {
            get {
                return ResourceManager.GetString("AddCaseWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the name and the email address for the new case worker..
        /// </summary>
        public static string AddCWInstr {
            get {
                return ResourceManager.GetString("AddCWInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Goal.
        /// </summary>
        public static string AddGoal {
            get {
                return ResourceManager.GetString("AddGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Guardian.
        /// </summary>
        public static string AddGuardian {
            get {
                return ResourceManager.GetString("AddGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Policy.
        /// </summary>
        public static string AddPolicy {
            get {
                return ResourceManager.GetString("AddPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Program.
        /// </summary>
        public static string AddProgram {
            get {
                return ResourceManager.GetString("AddProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Rate.
        /// </summary>
        public static string ClientRate {
            get {
                return ResourceManager.GetString("ClientRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Search Filter.
        /// </summary>
        public static string ClientSearchFilter {
            get {
                return ResourceManager.GetString("ClientSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment was successfully added to the client record..
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your comment here.
        /// </summary>
        public static string CommentInstr {
            get {
                return ResourceManager.GetString("CommentInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been recorded..
        /// </summary>
        public static string CommentRecorded {
            get {
                return ResourceManager.GetString("CommentRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to supply your comment text!.
        /// </summary>
        public static string CommentTextRequired {
            get {
                return ResourceManager.GetString("CommentTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor(s).
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPT Assignments.
        /// </summary>
        public static string CPTAssignments {
            get {
                return ResourceManager.GetString("CPTAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPT Code Assignment.
        /// </summary>
        public static string CPTCodeAssignment {
            get {
                return ResourceManager.GetString("CPTCodeAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new client was successfully created..
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this guardian?.
        /// </summary>
        public static string DeleteGuardianInstructions {
            get {
                return ResourceManager.GetString("DeleteGuardianInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this insurance policy from this client?.
        /// </summary>
        public static string DeletePolicyInstr {
            get {
                return ResourceManager.GetString("DeletePolicyInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this service from this client?.
        /// </summary>
        public static string DeleteSvcInstr {
            get {
                return ResourceManager.GetString("DeleteSvcInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Waiver.
        /// </summary>
        public static string DeleteWaiver {
            get {
                return ResourceManager.GetString("DeleteWaiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following waiver?.
        /// </summary>
        public static string DelWaiverInstr {
            get {
                return ResourceManager.GetString("DelWaiverInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this service to this client today and cancel any future appointements tied to this service?.
        /// </summary>
        public static string DiscSvcInstr {
            get {
                return ResourceManager.GetString("DiscSvcInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document was successfully attached to the client..
        /// </summary>
        public static string DocumentAttached {
            get {
                return ResourceManager.GetString("DocumentAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document was successfully removed from the client..
        /// </summary>
        public static string DocumentRemoved {
            get {
                return ResourceManager.GetString("DocumentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client Profile.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Government Assistance.
        /// </summary>
        public static string EditGovt {
            get {
                return ResourceManager.GetString("EditGovt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Guardian.
        /// </summary>
        public static string EditGuardian {
            get {
                return ResourceManager.GetString("EditGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file submitted was larger than 10MB..
        /// </summary>
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency &amp; Duration.
        /// </summary>
        public static string FreqDur {
            get {
                return ResourceManager.GetString("FreqDur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} {2}.
        /// </summary>
        public static string GoalCondition {
            get {
                return ResourceManager.GetString("GoalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal was successfully created for the client!.
        /// </summary>
        public static string GoalCreated {
            get {
                return ResourceManager.GetString("GoalCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal History.
        /// </summary>
        public static string GoalHistory {
            get {
                return ResourceManager.GetString("GoalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government assistance values have been updated successfully..
        /// </summary>
        public static string GovtValuesUpdated {
            get {
                return ResourceManager.GetString("GovtValuesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guardian was successfully updated.
        /// </summary>
        public static string GuardianCreated {
            get {
                return ResourceManager.GetString("GuardianCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information the same as client.
        /// </summary>
        public static string GuardianMatch {
            get {
                return ResourceManager.GetString("GuardianMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guardian was successfully removed.
        /// </summary>
        public static string GuardianRemoved {
            get {
                return ResourceManager.GetString("GuardianRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guardian was successfully updated.
        /// </summary>
        public static string GuardianUpdated {
            get {
                return ResourceManager.GetString("GuardianUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Waivers.
        /// </summary>
        public static string HasWaivers {
            get {
                return ResourceManager.GetString("HasWaivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scheduled Session.
        /// </summary>
        public static string LastScheduled {
            get {
                return ResourceManager.GetString("LastScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Comment.
        /// </summary>
        public static string MakeComment {
            get {
                return ResourceManager.GetString("MakeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no history for the selected goal.
        /// </summary>
        public static string NoHistoryForGoal {
            get {
                return ResourceManager.GetString("NoHistoryForGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Needed.
        /// </summary>
        public static string NoneNeeded {
            get {
                return ResourceManager.GetString("NoneNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Notes &amp; Reviews.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician Name.
        /// </summary>
        public static string PhysicianName {
            get {
                return ResourceManager.GetString("PhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance policy was added to the client..
        /// </summary>
        public static string PolicyCreated {
            get {
                return ResourceManager.GetString("PolicyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance policy was removed..
        /// </summary>
        public static string PolicyRemoved {
            get {
                return ResourceManager.GetString("PolicyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance policy was updated..
        /// </summary>
        public static string PolicyUpdated {
            get {
                return ResourceManager.GetString("PolicyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Guardian.
        /// </summary>
        public static string PrimaryGuardian {
            get {
                return ResourceManager.GetString("PrimaryGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Pay.
        /// </summary>
        public static string PrivatePay {
            get {
                return ResourceManager.GetString("PrivatePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Client Lookup.
        /// </summary>
        public static string QuickLookup {
            get {
                return ResourceManager.GetString("QuickLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following file from this client&apos;s record?.
        /// </summary>
        public static string RemoveDocConfirm {
            get {
                return ResourceManager.GetString("RemoveDocConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this client from the government assistance program?.
        /// </summary>
        public static string RemoveProgram {
            get {
                return ResourceManager.GetString("RemoveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was successfully created and is ready for editing..
        /// </summary>
        public static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Appointment(s).
        /// </summary>
        public static string ScheduleAppt {
            get {
                return ResourceManager.GetString("ScheduleAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully added.
        /// </summary>
        public static string ServiceAdded {
            get {
                return ResourceManager.GetString("ServiceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully deleted.
        /// </summary>
        public static string ServiceDeleted {
            get {
                return ResourceManager.GetString("ServiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service/Discipline.
        /// </summary>
        public static string ServiceDisc {
            get {
                return ResourceManager.GetString("ServiceDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully discontinued.
        /// </summary>
        public static string ServiceEnded {
            get {
                return ResourceManager.GetString("ServiceEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client has services starting before the start of their authorization..
        /// </summary>
        public static string ServicesBeforeAuth {
            get {
                return ResourceManager.GetString("ServicesBeforeAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has services where the last scheduled appointment is within the next 2 weeks..
        /// </summary>
        public static string ServicesExpiring {
            get {
                return ResourceManager.GetString("ServicesExpiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully updated.
        /// </summary>
        public static string ServiceUpdated {
            get {
                return ResourceManager.GetString("ServiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string SessionsScheduled {
            get {
                return ResourceManager.GetString("SessionsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service starts before it is authorized..
        /// </summary>
        public static string StartsBeforeAuth {
            get {
                return ResourceManager.GetString("StartsBeforeAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client&apos;s profile information was successfully updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Insurance Policy.
        /// </summary>
        public static string UpdatePolicy {
            get {
                return ResourceManager.GetString("UpdatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Service.
        /// </summary>
        public static string UpdateService {
            get {
                return ResourceManager.GetString("UpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Prescription.
        /// </summary>
        public static string ViewRx {
            get {
                return ResourceManager.GetString("ViewRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government assistance waiver has been added.
        /// </summary>
        public static string WaiverAdded {
            get {
                return ResourceManager.GetString("WaiverAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government assistance waiver has been confirmed..
        /// </summary>
        public static string WaiverConfirmed {
            get {
                return ResourceManager.GetString("WaiverConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government assistance waiver has been removed.
        /// </summary>
        public static string WaiverRemoved {
            get {
                return ResourceManager.GetString("WaiverRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Assistance Waivers.
        /// </summary>
        public static string Waivers {
            get {
                return ResourceManager.GetString("Waivers", resourceCulture);
            }
        }
    }
}
