//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.CompanyPages", typeof(CompanyPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the provider id you have with the following program: .
        /// </summary>
        public static string AddGovtInstr {
            get {
                return ResourceManager.GetString("AddGovtInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Government Program.
        /// </summary>
        public static string AddGovtProgram {
            get {
                return ResourceManager.GetString("AddGovtProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Insurance Company.
        /// </summary>
        public static string AddInsurance {
            get {
                return ResourceManager.GetString("AddInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add the following insurance company?.
        /// </summary>
        public static string AddInsuranceInstr {
            get {
                return ResourceManager.GetString("AddInsuranceInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance company was successfully added as a pay option.
        /// </summary>
        public static string InsuranceAdded {
            get {
                return ResourceManager.GetString("InsuranceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance company was successfully removed as a pay option.
        /// </summary>
        public static string InsuranceRemoved {
            get {
                return ResourceManager.GetString("InsuranceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government program was successfully added as a pay option.
        /// </summary>
        public static string ProgramAdded {
            get {
                return ResourceManager.GetString("ProgramAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The government program was successfully removed as a pay option.
        /// </summary>
        public static string ProgramRemoved {
            get {
                return ResourceManager.GetString("ProgramRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this government program? .
        /// </summary>
        public static string RemoveGovtInstr {
            get {
                return ResourceManager.GetString("RemoveGovtInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Government Program.
        /// </summary>
        public static string RemoveGovtProgram {
            get {
                return ResourceManager.GetString("RemoveGovtProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Insurance Company.
        /// </summary>
        public static string RemoveInsurance {
            get {
                return ResourceManager.GetString("RemoveInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this insurance company? .
        /// </summary>
        public static string RemoveInsuranceInstr {
            get {
                return ResourceManager.GetString("RemoveInsuranceInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact information for the company was successfully updated..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
