//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CredentialPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CredentialPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.CredentialPages", typeof(CredentialPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking.
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the new image of the credential..
        /// </summary>
        public static string ChangeImageInstr {
            get {
                return ResourceManager.GetString("ChangeImageInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Of Credential.
        /// </summary>
        public static string CopyOfCredential {
            get {
                return ResourceManager.GetString("CopyOfCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Credential.
        /// </summary>
        public static string CreateCredential {
            get {
                return ResourceManager.GetString("CreateCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this credential?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully deleted the credential..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Credential.
        /// </summary>
        public static string EditCredential {
            get {
                return ResourceManager.GetString("EditCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential files must be under 3MB in size..
        /// </summary>
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to ignore this credential..
        /// </summary>
        public static string IgnoreInstr {
            get {
                return ResourceManager.GetString("IgnoreInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text of the message you want to send about this credential..
        /// </summary>
        public static string MsgInstr {
            get {
                return ResourceManager.GetString("MsgInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Required.
        /// </summary>
        public static string NbrRequired {
            get {
                return ResourceManager.GetString("NbrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the image of this credential?.
        /// </summary>
        public static string RemoveImageInstr {
            get {
                return ResourceManager.GetString("RemoveImageInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credential requirment changes have been saved..
        /// </summary>
        public static string RequirementsSaved {
            get {
                return ResourceManager.GetString("RequirementsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member.
        /// </summary>
        public static string StaffMember {
            get {
                return ResourceManager.GetString("StaffMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully added a new credential to your profile.
        /// </summary>
        public static string SuccessCreatedCredential {
            get {
                return ResourceManager.GetString("SuccessCreatedCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image of the credential has been changed..
        /// </summary>
        public static string SuccessImageChanged {
            get {
                return ResourceManager.GetString("SuccessImageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image of the credential has been removed..
        /// </summary>
        public static string SuccessImageRemoved {
            get {
                return ResourceManager.GetString("SuccessImageRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully updated your credential..
        /// </summary>
        public static string SuccessUpdatedCredential {
            get {
                return ResourceManager.GetString("SuccessUpdatedCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown credential was requested.
        /// </summary>
        public static string UnknownCredential {
            get {
                return ResourceManager.GetString("UnknownCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified At.
        /// </summary>
        public static string VerifiedAt {
            get {
                return ResourceManager.GetString("VerifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified By.
        /// </summary>
        public static string VerifiedBy {
            get {
                return ResourceManager.GetString("VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Credentials.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to verify this credential..
        /// </summary>
        public static string VerifyInstr {
            get {
                return ResourceManager.GetString("VerifyInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to watch this credential..
        /// </summary>
        public static string WatchInstr {
            get {
                return ResourceManager.GetString("WatchInstr", resourceCulture);
            }
        }
    }
}
