//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisciplinePages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisciplinePages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.DisciplinePages", typeof(DisciplinePages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discipline was successfully activated..
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Goal Area.
        /// </summary>
        public static string AddGoalArea {
            get {
                return ResourceManager.GetString("AddGoalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discipline was successfully created.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discipline was successfully deactivated..
        /// </summary>
        public static string DeactivateSuccess {
            get {
                return ResourceManager.GetString("DeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Discipline.
        /// </summary>
        public static string EditDiscipline {
            get {
                return ResourceManager.GetString("EditDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Areas.
        /// </summary>
        public static string GoalAreas {
            get {
                return ResourceManager.GetString("GoalAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a name for the discipline.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Discipline Name.
        /// </summary>
        public static string NewDisciplineName {
            get {
                return ResourceManager.GetString("NewDisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no frequency/durations for the selected discipline..
        /// </summary>
        public static string NoDurations {
            get {
                return ResourceManager.GetString("NoDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pay rates for the selected discipline..
        /// </summary>
        public static string NoPayRates {
            get {
                return ResourceManager.GetString("NoPayRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no providers for the selected discipline..
        /// </summary>
        public static string NoProviders {
            get {
                return ResourceManager.GetString("NoProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Discipline.
        /// </summary>
        public static string RemoveDiscipline {
            get {
                return ResourceManager.GetString("RemoveDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following discipline? .
        /// </summary>
        public static string RemoveDisciplineInstr {
            get {
                return ResourceManager.GetString("RemoveDisciplineInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discipline was successfully removed..
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Report Questions.
        /// </summary>
        public static string ReportQuestions {
            get {
                return ResourceManager.GetString("ReportQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discipline was successfully updated..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
