//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FreqDurPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FreqDurPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.FreqDurPages", typeof(FreqDurPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency/duration was successfully activated.
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Frequency/Duration.
        /// </summary>
        public static string AddRate {
            get {
                return ResourceManager.GetString("AddRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency/duration was created.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency/duration was successfully deactivated.
        /// </summary>
        public static string DeactivateSuccess {
            get {
                return ResourceManager.GetString("DeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Frequency/Duration.
        /// </summary>
        public static string EditRate {
            get {
                return ResourceManager.GetString("EditRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5x per Week.
        /// </summary>
        public static string FiveWeek {
            get {
                return ResourceManager.GetString("FiveWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x per Week.
        /// </summary>
        public static string FourWeek {
            get {
                return ResourceManager.GetString("FourWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Frequency/ Duration.
        /// </summary>
        public static string RemoveRate {
            get {
                return ResourceManager.GetString("RemoveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this frequency/duration?.
        /// </summary>
        public static string RemoveRateInstr {
            get {
                return ResourceManager.GetString("RemoveRateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency/duration was removed.
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-weekly.
        /// </summary>
        public static string Semiweekly {
            get {
                return ResourceManager.GetString("Semiweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6x per Week.
        /// </summary>
        public static string SixWeek {
            get {
                return ResourceManager.GetString("SixWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x per Week.
        /// </summary>
        public static string ThreeWeek {
            get {
                return ResourceManager.GetString("ThreeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x Per Week.
        /// </summary>
        public static string TwoWeek {
            get {
                return ResourceManager.GetString("TwoWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency/duration was updated.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
