//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoalAreaPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoalAreaPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.GoalAreaPages", typeof(GoalAreaPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal area was successfully activated.
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new goal area has been successfully created.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Goal Template.
        /// </summary>
        public static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal template was successfully created.
        /// </summary>
        public static string CreateTemplateSuccess {
            get {
                return ResourceManager.GetString("CreateTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal area was successfully deactivated.
        /// </summary>
        public static string DeactivateSuccess {
            get {
                return ResourceManager.GetString("DeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Goal Area.
        /// </summary>
        public static string EditArea {
            get {
                return ResourceManager.GetString("EditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Goal Template.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name for the new goal area is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Goal Area.
        /// </summary>
        public static string RemoveArea {
            get {
                return ResourceManager.GetString("RemoveArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this goal area?.
        /// </summary>
        public static string RemoveAreaInstr {
            get {
                return ResourceManager.GetString("RemoveAreaInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal area was successfully removed.
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Template.
        /// </summary>
        public static string RemoveTemplate {
            get {
                return ResourceManager.GetString("RemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following goal template?.
        /// </summary>
        public static string RemoveTemplateInstr {
            get {
                return ResourceManager.GetString("RemoveTemplateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal template was successfully removed.
        /// </summary>
        public static string RemoveTemplateSuccess {
            get {
                return ResourceManager.GetString("RemoveTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area name was successfully saved..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal template was successfully updated.
        /// </summary>
        public static string UpdateTemplateSuccess {
            get {
                return ResourceManager.GetString("UpdateTemplateSuccess", resourceCulture);
            }
        }
    }
}
