//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotePages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotePages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.NotePages", typeof(NotePages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Goal.
        /// </summary>
        public static string AddGoal {
            get {
                return ResourceManager.GetString("AddGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your recommendation for continuing the service or ending it. Choosing to end the service will cancel all future appointments under this service..
        /// </summary>
        public static string ApproveInstr {
            get {
                return ResourceManager.GetString("ApproveInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes were successfully approved..
        /// </summary>
        public static string ApproveSuccess {
            get {
                return ResourceManager.GetString("ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Areas Worked On.
        /// </summary>
        public static string AreasWorked {
            get {
                return ResourceManager.GetString("AreasWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit this evaluation? Changes cannot be made once it is submitted..
        /// </summary>
        public static string ConfirmSubmit {
            get {
                return ResourceManager.GetString("ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment was successfully added to the notes.
        /// </summary>
        public static string FileAttached {
            get {
                return ResourceManager.GetString("FileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was selected.
        /// </summary>
        public static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment was successfully removed from the notes.
        /// </summary>
        public static string FileRemoved {
            get {
                return ResourceManager.GetString("FileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pending goal was successfully added to the note..
        /// </summary>
        public static string GoalCreated {
            get {
                return ResourceManager.GetString("GoalCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pending goal has been successfully removed.
        /// </summary>
        public static string GoalRemoved {
            get {
                return ResourceManager.GetString("GoalRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals To Add.
        /// </summary>
        public static string GoalsToAdd {
            get {
                return ResourceManager.GetString("GoalsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Updates.
        /// </summary>
        public static string GoalUpdates {
            get {
                return ResourceManager.GetString("GoalUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Goals.
        /// </summary>
        public static string HighlightGoals {
            get {
                return ResourceManager.GetString("HighlightGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Goals.
        /// </summary>
        public static string NewGoals {
            get {
                return ResourceManager.GetString("NewGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 1 or more recipients to share the document with..
        /// </summary>
        public static string NoDestination {
            get {
                return ResourceManager.GetString("NoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes/Questions.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Session Notes.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Notes Pending Review.
        /// </summary>
        public static string PendingReview {
            get {
                return ResourceManager.GetString("PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the reason you are rejecting these notes so that the issues may be resolved..
        /// </summary>
        public static string RejectInstr {
            get {
                return ResourceManager.GetString("RejectInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes were successfully rejected..
        /// </summary>
        public static string RejectSuccess {
            get {
                return ResourceManager.GetString("RejectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Attachment.
        /// </summary>
        public static string RemoveAttachment {
            get {
                return ResourceManager.GetString("RemoveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this file from the notes?.
        /// </summary>
        public static string RemoveAttachmentInstr {
            get {
                return ResourceManager.GetString("RemoveAttachmentInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Goal.
        /// </summary>
        public static string RemoveGoal {
            get {
                return ResourceManager.GetString("RemoveGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you no longer want to add the following goal to the client upon submission?.
        /// </summary>
        public static string RemoveGoalInstr {
            get {
                return ResourceManager.GetString("RemoveGoalInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save your initial draft of the session notes before you can create goals to add to this client upon submission..
        /// </summary>
        public static string SaveBeforeAdd {
            get {
                return ResourceManager.GetString("SaveBeforeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save your initial draft of the session notes before you can attach files to them..
        /// </summary>
        public static string SaveBeforeAttach {
            get {
                return ResourceManager.GetString("SaveBeforeAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your edits were successfully saved.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Notes.
        /// </summary>
        public static string SessionNotes {
            get {
                return ResourceManager.GetString("SessionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whom to send emails to in order to share these session notes with..
        /// </summary>
        public static string ShareInstr {
            get {
                return ResourceManager.GetString("ShareInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes have been successfully shared with the selected people. They will be receiving an email shortly with a secure link to the notes..
        /// </summary>
        public static string ShareSuccess {
            get {
                return ResourceManager.GetString("ShareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes were successfully submitted.
        /// </summary>
        public static string SubmissionSuccess {
            get {
                return ResourceManager.GetString("SubmissionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
