//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicePages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicePages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.ServicePages", typeof(ServicePages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully activated.
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddRate {
            get {
                return ResourceManager.GetString("AddRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed CPT Codes.
        /// </summary>
        public static string AllowedCPTs {
            get {
                return ResourceManager.GetString("AllowedCPTs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Frequency &amp; Durations.
        /// </summary>
        public static string AllowedFreqs {
            get {
                return ResourceManager.GetString("AllowedFreqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows Payment Rates.
        /// </summary>
        public static string AllowedRates {
            get {
                return ResourceManager.GetString("AllowedRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was created.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully deactivated.
        /// </summary>
        public static string DeactivateSuccess {
            get {
                return ResourceManager.GetString("DeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string EditRate {
            get {
                return ResourceManager.GetString("EditRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Note Questions.
        /// </summary>
        public static string NoteQuestions {
            get {
                return ResourceManager.GetString("NoteQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Service.
        /// </summary>
        public static string RemoveRate {
            get {
                return ResourceManager.GetString("RemoveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this service?.
        /// </summary>
        public static string RemoveRateInstr {
            get {
                return ResourceManager.GetString("RemoveRateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was removed.
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was updated.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
