//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.SettingsPages", typeof(SettingsPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may find more information about accessing the API at {0}..
        /// </summary>
        public static string APIAccessInfo {
            get {
                return ResourceManager.GetString("APIAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API interface for this account has been disabled..
        /// </summary>
        public static string APIDisabled {
            get {
                return ResourceManager.GetString("APIDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API interface for this account has been enabled..
        /// </summary>
        public static string APIEnabled {
            get {
                return ResourceManager.GetString("APIEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the API to pull information out of Therapy Corner into another system of yours or to simply pull into another application to make your own dashboards and reports..
        /// </summary>
        public static string APIInstructions {
            get {
                return ResourceManager.GetString("APIInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passcode on the API interface for this account has been changed..
        /// </summary>
        public static string APIReset {
            get {
                return ResourceManager.GetString("APIReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the following values into the header of any request you make to the API..
        /// </summary>
        public static string APISettingInfo {
            get {
                return ResourceManager.GetString("APISettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable API.
        /// </summary>
        public static string ClearAPI {
            get {
                return ResourceManager.GetString("ClearAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance clearing house has been updated for this account..
        /// </summary>
        public static string ClearingHouseUpdated {
            get {
                return ResourceManager.GetString("ClearingHouseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable the API interface on this account?.
        /// </summary>
        public static string ConfirmClearAPI {
            get {
                return ResourceManager.GetString("ConfirmClearAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the API interface password on this account? When you do, you will need to change the code used on all applications interacting with the API to the new one that will be displayed..
        /// </summary>
        public static string ConfirmResetAPI {
            get {
                return ResourceManager.GetString("ConfirmResetAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable the API interface on this account?.
        /// </summary>
        public static string ConfirmSetAPI {
            get {
                return ResourceManager.GetString("ConfirmSetAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You integration options have been successfully updated..
        /// </summary>
        public static string IntegrationsUpdated {
            get {
                return ResourceManager.GetString("IntegrationsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounting integration choice has been made yet. Please click on a button below to begin integrating payroll, expenses, and payments with the accounting system of your choice..
        /// </summary>
        public static string NoAccountingIntegration {
            get {
                return ResourceManager.GetString("NoAccountingIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the requested action because this account is not linked to QuickBooks..
        /// </summary>
        public static string NotLinkedToQB {
            get {
                return ResourceManager.GetString("NotLinkedToQB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the ID for your account that can be found by looking at the &quot;Your Account&quot; screen in QuickBooks under the settings menu..
        /// </summary>
        public static string QBCompanyHelp {
            get {
                return ResourceManager.GetString("QBCompanyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickBooks returned the following error while trying to establish the connection with Therapy Corner: {0}.
        /// </summary>
        public static string QBLinkError {
            get {
                return ResourceManager.GetString("QBLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully linked this account to QuickBooks..
        /// </summary>
        public static string QBLinkSuccess {
            get {
                return ResourceManager.GetString("QBLinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must renew the link between Therapy Corner and QuickBooks annually..
        /// </summary>
        public static string QBRenewHelp {
            get {
                return ResourceManager.GetString("QBRenewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system performed a sync where possible with QuickBooks..
        /// </summary>
        public static string QBSyncd {
            get {
                return ResourceManager.GetString("QBSyncd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickBooks.
        /// </summary>
        public static string QuickBooks {
            get {
                return ResourceManager.GetString("QuickBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Link.
        /// </summary>
        public static string RefreshLink {
            get {
                return ResourceManager.GetString("RefreshLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        public static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset API Code.
        /// </summary>
        public static string ResetAPI {
            get {
                return ResourceManager.GetString("ResetAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable API.
        /// </summary>
        public static string SetAPI {
            get {
                return ResourceManager.GetString("SetAPI", resourceCulture);
            }
        }
    }
}
