//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.SharedPages", typeof(SharedPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Used to Support Therapeutic Strategies.
        /// </summary>
        public static string ActivitiesOutcome {
            get {
                return ResourceManager.GetString("ActivitiesOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Forgery Error.
        /// </summary>
        public static string AntiForgeryError {
            get {
                return ResourceManager.GetString("AntiForgeryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have hit this page because you have submitted a request to Therapy Corner in a way that indicated that it was not you who made the request. This usually happens when you click back on your web browser and then try clicking on the button or link again. Or if your session has timed out. If you believe you reached this page in error, please click on the back button on your web browser and then on the refresh button. This will trigger your web browser to ensure it has all of the proper information to authen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AntiForgeryErrorInstr {
            get {
                return ResourceManager.GetString("AntiForgeryErrorInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Filter.
        /// </summary>
        public static string ChangeFilter {
            get {
                return ResourceManager.GetString("ChangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within 30 Days.
        /// </summary>
        public static string Claims30 {
            get {
                return ResourceManager.GetString("Claims30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30-60 Days.
        /// </summary>
        public static string Claims60 {
            get {
                return ResourceManager.GetString("Claims60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60+ Days.
        /// </summary>
        public static string Claims90 {
            get {
                return ResourceManager.GetString("Claims90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Req Attention.
        /// </summary>
        public static string ClaimsReqAttention {
            get {
                return ResourceManager.GetString("ClaimsReqAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be associated with a company in order to access this feature..
        /// </summary>
        public static string CompanyRequired {
            get {
                return ResourceManager.GetString("CompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your request could not be processed since you had to log back in. .
        /// </summary>
        public static string CouldNotProcessRelogin {
            get {
                return ResourceManager.GetString("CouldNotProcessRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Couldn&apos;t Find Your Page! (404 Error).
        /// </summary>
        public static string CouldntFindPage {
            get {
                return ResourceManager.GetString("CouldntFindPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Requirements.
        /// </summary>
        public static string CredentialRequirements {
            get {
                return ResourceManager.GetString("CredentialRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user context menu.
        /// </summary>
        public static string DisplayMenu {
            get {
                return ResourceManager.GetString("DisplayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you will download upon verification is a secured file. Do not create a bookmark in your web browser to it because you must re-confirm your identity everytime you access the file. Rather just save the file to your local device..
        /// </summary>
        public static string DoNotBookMarkSecured {
            get {
                return ResourceManager.GetString("DoNotBookMarkSecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while processing your request. Feel free to try the action you just attempted again.  If the error re-occurs please contact customer support..
        /// </summary>
        public static string ErrorNotification {
            get {
                return ResourceManager.GetString("ErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Credentials.
        /// </summary>
        public static string ExpCredentials {
            get {
                return ResourceManager.GetString("ExpCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Action.
        /// </summary>
        public static string GoalAction {
            get {
                return ResourceManager.GetString("GoalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the page you&apos;ve requested cannot be displayed. It appears that you&apos;ve lost your way either through an outdated link or a typo on the page you were trying to reach..
        /// </summary>
        public static string Http404Instr {
            get {
                return ResourceManager.GetString("Http404Instr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Staff.
        /// </summary>
        public static string InviteStaff {
            get {
                return ResourceManager.GetString("InviteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out of Therapy Corner..
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Fields.
        /// </summary>
        public static string MatrixFields {
            get {
                return ResourceManager.GetString("MatrixFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Credentials.
        /// </summary>
        public static string MissingCredentials {
            get {
                return ResourceManager.GetString("MissingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Missing Rx.
        /// </summary>
        public static string MissingRx {
            get {
                return ResourceManager.GetString("MissingRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Finance Summary.
        /// </summary>
        public static string MySummary {
            get {
                return ResourceManager.GetString("MySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Clients.
        /// </summary>
        public static string NbrClients {
            get {
                return ResourceManager.GetString("NbrClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services To Schedule.
        /// </summary>
        public static string NeedScheduling {
            get {
                return ResourceManager.GetString("NeedScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Messages.
        /// </summary>
        public static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Pending Review.
        /// </summary>
        public static string NotesReview {
            get {
                return ResourceManager.GetString("NotesReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching OIG Exceptions.
        /// </summary>
        public static string OIGExceptions {
            get {
                return ResourceManager.GetString("OIGExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Count.
        /// </summary>
        public static string Patientcount {
            get {
                return ResourceManager.GetString("Patientcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Session Notes.
        /// </summary>
        public static string PendingNotes {
            get {
                return ResourceManager.GetString("PendingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reports.
        /// </summary>
        public static string PendingReports {
            get {
                return ResourceManager.GetString("PendingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Validations.
        /// </summary>
        public static string PendingValidations {
            get {
                return ResourceManager.GetString("PendingValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Validations.
        /// </summary>
        public static string PendingVals {
            get {
                return ResourceManager.GetString("PendingVals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Make-ups.
        /// </summary>
        public static string PotMakeups {
            get {
                return ResourceManager.GetString("PotMakeups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is being processed....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress On Outcome.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Count.
        /// </summary>
        public static string ProviderCount {
            get {
                return ResourceManager.GetString("ProviderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations/Changes.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Pending Review.
        /// </summary>
        public static string ReportsReview {
            get {
                return ResourceManager.GetString("ReportsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles at {0}.
        /// </summary>
        public static string RolesAt {
            get {
                return ResourceManager.GetString("RolesAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Reminder.
        /// </summary>
        public static string SaveReminder {
            get {
                return ResourceManager.GetString("SaveReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to save your work every so often so that your session does not expire and you loose your changes. Would you like to save now?.
        /// </summary>
        public static string SaveReminderText {
            get {
                return ResourceManager.GetString("SaveReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Session(s).
        /// </summary>
        public static string ScheduleSessions {
            get {
                return ResourceManager.GetString("ScheduleSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service/Client Counts.
        /// </summary>
        public static string ServiceClientCounts {
            get {
                return ResourceManager.GetString("ServiceClientCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Count.
        /// </summary>
        public static string ServiceCount {
            get {
                return ResourceManager.GetString("ServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please logout and log back in..
        /// </summary>
        public static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cancelled.
        /// </summary>
        public static string ShowCancelled {
            get {
                return ResourceManager.GetString("ShowCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Fields.
        /// </summary>
        public static string StaffFields {
            get {
                return ResourceManager.GetString("StaffFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Matrix.
        /// </summary>
        public static string StaffMatrix {
            get {
                return ResourceManager.GetString("StaffMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategies/Activities Used to Address Outcome.
        /// </summary>
        public static string Strategies {
            get {
                return ResourceManager.GetString("Strategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategies Used to Address Outcome.
        /// </summary>
        public static string StrategiesOutcome {
            get {
                return ResourceManager.GetString("StrategiesOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapy Corner Error.
        /// </summary>
        public static string TCError {
            get {
                return ResourceManager.GetString("TCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved Services.
        /// </summary>
        public static string UnapprovedServices {
            get {
                return ResourceManager.GetString("UnapprovedServices", resourceCulture);
            }
        }
    }
}
