//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TherapyCorner.Portal.ResourceText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaffPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaffPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TherapyCorner.Portal.ResourceText.StaffPages", typeof(StaffPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the service you would like to add to this staff member..
        /// </summary>
        public static string AddServiceInstr {
            get {
                return ResourceManager.GetString("AddServiceInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more services that can be added to this staff member..
        /// </summary>
        public static string AddServiceNone {
            get {
                return ResourceManager.GetString("AddServiceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments were successfully scheduled!.
        /// </summary>
        public static string AppointmentsScheduled {
            get {
                return ResourceManager.GetString("AppointmentsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payroll Rate.
        /// </summary>
        public static string EditPayRate {
            get {
                return ResourceManager.GetString("EditPayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Staff.
        /// </summary>
        public static string EditStaff {
            get {
                return ResourceManager.GetString("EditStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Initial.
        /// </summary>
        public static string FirstInitial {
            get {
                return ResourceManager.GetString("FirstInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Staff.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff member was successfully invited..
        /// </summary>
        public static string InviteSuccess {
            get {
                return ResourceManager.GetString("InviteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Staff Appointment.
        /// </summary>
        public static string MakeAppt {
            get {
                return ResourceManager.GetString("MakeAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Points.
        /// </summary>
        public static string MatchPoints {
            get {
                return ResourceManager.GetString("MatchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Initial.
        /// </summary>
        public static string MiddleInitial {
            get {
                return ResourceManager.GetString("MiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There currently are no staff members that may match individuals on the OIG Exclusion list.
        /// </summary>
        public static string NoOIGMatches {
            get {
                return ResourceManager.GetString("NoOIGMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payroll rate was successfully changed!.
        /// </summary>
        public static string PayRateSuccess {
            get {
                return ResourceManager.GetString("PayRateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reports.
        /// </summary>
        public static string PendingReports {
            get {
                return ResourceManager.GetString("PendingReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed all roles from this staff member. This will remove all access this user has to the company information on Therapy Corner. Are you sure you want to do this?.
        /// </summary>
        public static string RemoveConfirm {
            get {
                return ResourceManager.GetString("RemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string RemoveService {
            get {
                return ResourceManager.GetString("RemoveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following service from this staff member?.
        /// </summary>
        public static string RemoveServiceInstr {
            get {
                return ResourceManager.GetString("RemoveServiceInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Staff.
        /// </summary>
        public static string RemoveTitle {
            get {
                return ResourceManager.GetString("RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This staff member has {0} pending reports to complete..
        /// </summary>
        public static string ReportCountWarning {
            get {
                return ResourceManager.GetString("ReportCountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Invite.
        /// </summary>
        public static string ResendInvite {
            get {
                return ResourceManager.GetString("ResendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invite was successfully resent..
        /// </summary>
        public static string ResendSuccess {
            get {
                return ResourceManager.GetString("ResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Staff.
        /// </summary>
        public static string SearchStaff {
            get {
                return ResourceManager.GetString("SearchStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was successfully added..
        /// </summary>
        public static string ServiceAdded {
            get {
                return ResourceManager.GetString("ServiceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Details.
        /// </summary>
        public static string StaffDetails {
            get {
                return ResourceManager.GetString("StaffDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Search Filter.
        /// </summary>
        public static string StaffSearchFilter {
            get {
                return ResourceManager.GetString("StaffSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff member information was successfully updated..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
